name: Sync Profile README

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Copy README to other repos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPOS=("GKI_KernelSU_SUSFS")  # Your repository name

          for REPO in "${REPOS[@]}"; do
            git clone https://github.com/WildPlusKernel/$REPO.git
            cd $REPO

            cp ../profile/README.md README.md
            git config user.name "TheWildJames"
            git config user.email "bins4us@hotmail.com"

            git add README.md
            git commit -m "Sync README from profile" || echo "No changes to commit"
            git push

            cd ..
            rm -rf $REPO
          done
