name: Sync Profile README

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Copy README to other repos
        run: |
          REPOS=("GKI_KernelSU_SUSFS" "Sultan_KernelSU_SUSFS" "OnePlus_KernelSU_SUSFS" "Pixel_KernelSU_SUSFS")

          for REPO in "${REPOS[@]}"; do
            echo "Processing $REPO..."
            git clone https://github.com/WildKernels/$REPO.git $REPO
            if [ $? -ne 0 ]; then
              echo "Failed to clone $REPO"
              continue
            fi

            cd $REPO

            # Detect the default branch
            DEFAULT_BRANCH=$(git ls-remote --symref origin HEAD | grep 'ref: refs/heads/' | sed 's|.*refs/heads/||' | sed 's|\s.*||')
            if [ -z "$DEFAULT_BRANCH" ]; then
              echo "Failed to detect default branch for $REPO, assuming 'main'"
              DEFAULT_BRANCH="main"
            fi
            echo "Default branch for $REPO is $DEFAULT_BRANCH"

            # Ensure the default branch is checked out
            git checkout $DEFAULT_BRANCH || git checkout -b $DEFAULT_BRANCH

            cp ../profile/README.md README.md
            git config user.name "TheWildJames"
            git config user.email "bins4us@hotmail.com"

            git add README.md
            git commit -m "Sync README from profile" || echo "No changes to commit in $REPO"
            git push https://x-access-token:$GH_TOKEN@github.com/WildKernels/$REPO.git $DEFAULT_BRANCH
            if [ $? -ne 0 ]; then
              echo "Failed to push to $REPO"
            fi

            cd ..
            rm -rf $REPO
          done
